apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: kube-team3
  labels:
    run: tripviewer
spec:
  selector:
    run: tripviewer
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer