apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poi
  name: poi
  namespace: kube-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  strategy: {}
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: registrysub5559.azurecr.io/tripinsights/poi:1.0
        name: poi
        ports:
        - containerPort: 80
        resources: {}
        env:
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: azure-mssql
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                name: azure-mssql
                key: SQL_DBNAME
          - name: SQL_USER
            valueFrom:
              secretKeyRef: 
                name: azure-mssql-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: azure-mssql-secret
                key: SQL_PASSWORD
status: {}
