apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: trips
  name: trips
  namespace: kube-team3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  strategy: {}
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: registrysub5559.azurecr.io/tripinsights/trips:1.0
        name: trips
        ports:
        - containerPort: 80
        resources: {}
        env:
          - name: SQL_SERVER
            valueFrom:
              configMapKeyRef:
                name: azure-mssql
                key: SQL_SERVER
          - name: SQL_DBNAME
            valueFrom:
              configMapKeyRef:
                name: azure-mssql
                key: SQL_DBNAME
          - name: SQL_USER
            valueFrom:
              secretKeyRef: 
                name: azure-mssql-secret
                key: SQL_USER
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: azure-mssql-secret
                key: SQL_PASSWORD
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: trips
  name: trips-svc
  namespace: kube-team3
spec:
  selector:
    run: trips
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80