kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view
  namespace: web
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-view-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-view
subjects:
- kind: Group
  namespace: web
  name: 47484dae-316d-40fc-ba4b-5a0316148e6e