kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-edit-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-edit
subjects:
- kind: Group
  namespace: api
  name: 47484dae-316d-40fc-ba4b-5a0316148e6e