kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view
  namespace: api
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: web-view-binding
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-view
subjects:
- kind: Group
  namespace: api
  name: d2d34187-015b-487f-b6a5-ec6af488a31c